### ISSUE TITLE
gives error _load_textdomain_just_in_time was called incorrectly with new Wordpress version 6.7.1

### ISSUE THREAD

**Issue by deda-digital** [viivue/acf-icomoon#17]
Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the acf-icomoon domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /wp-includes/functions.php on line 6114

**Comment by daomapsieucap** [comment]
Hi @deda-digital,

Thanks for the detailed report, this issue was fixed and it'll be released in the next version. We'll let you know when the new version is ready.

**Comment by misthero** [comment]
Sorry but the problem is now worse, with the latest version I get:

Fatal error
: Uncaught Error: Call to undefined function ev_array_key_exists() in /opt/app-root/wordpress/wp-content/plugins/acf-icomoon/includes/fields/acf-field-icomoon.php:125 Stack trace: #0 /opt/app-root/wordpress/wp-content/plugins/acf-icomoon/includes/fields/acf-field-icomoon.php(247): ViiVue_ACF_Field_Icomoon->viivue_get_icomoon_json('') #1 /opt/app-root/wordpress/wp-includes/class-wp-hook.php(324): ViiVue_ACF_Field_Icomoon->format_value('icon-comunicato...', 'category_4085', Array, false) #2 /opt/app-root/wordpress/wp-includes/plugin.php(256): WP_Hook->apply_filters('icon-comunicato...', Array)

**Comment by daomapsieucap** [comment]
Sorry @misthero , could you update to the latest version 4.0.12 [here](https://wordpress.org/plugins/acf-icomoon/)

We're just released the version to fix this issue as you can follow up here: https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-undefined-function-ev_array_key_exists/#post-18355031

**Comment by misthero** [comment]
Yep, it works now thx for the fast response.
